/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogInFrame;

/**
 *
 * @author Lenovo
 */
public class LoginHeader extends javax.swing.JPanel {

    /**
     * Creates new form LoginHeader
     */
    public LoginHeader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientImageAvater1 = new ImageAvatar.GradientImageAvater();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(157, 153, 255));
        setForeground(new java.awt.Color(157, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientImageAvater1.setBorderSize(3);
        gradientImageAvater1.setBorderSpace(2);
        gradientImageAvater1.setGradientColor2(new java.awt.Color(240, 204, 16));
        gradientImageAvater1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user photo.jpg"))); // NOI18N
        add(gradientImageAvater1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 40, 50));

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daisy's Inventory Management System");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -6, 390, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ImageAvatar.GradientImageAvater gradientImageAvater1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
